import os
import pandas as pd
import streamlit as st
from datetime import datetime

# ==============================
# FOLDERS & FILES
# ==============================
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
LOGS_DIR = os.path.join(BASE_DIR, "logs")
LOG_FILE = os.path.join(LOGS_DIR, "signals_log.csv")

# ==============================
# STREAMLIT PAGE CONFIG
# ==============================
st.set_page_config(page_title="XAUUSD Signal Dashboard", layout="wide")
st.title("XAUUSD Advanced Signal Dashboard 📊")
st.markdown("Real-time signals generated by Phase 4 AI bot")

# ==============================
# LOAD DATA
# ==============================
if os.path.exists(LOG_FILE):
    df = pd.read_csv(LOG_FILE)
    df["time"] = pd.to_datetime(df["time"])
else:
    st.warning("No signals found yet. Run the bot first!")
    st.stop()

# ==============================
# LATEST SIGNAL
# ==============================
latest = df.iloc[-1]
st.subheader("Latest Signal")
st.markdown(f"""
Time: {latest['time']}  
Signal: {latest['signal']}  
Price: {latest['entry']:.2f}  
SL: {latest['sl']:.2f}  
TP1: {latest['tp1']:.2f} | TP2: {latest['tp2']:.2f} | TP3: {latest['tp3']:.2f} | TP4: {latest['tp4']:.2f}  
Session: {latest['session']}  
Confidence: {latest['confidence']}%
""")

# ==============================
# HISTORICAL SIGNALS
# ==============================
st.subheader("Historical Signals")
st.dataframe(df.sort_values(by="time", ascending=False))

# ==============================
# BASIC CHARTS
# ==============================
st.subheader("Signal Confidence Over Time")
st.line_chart(df[["confidence"]])

st.subheader("Signal Count")
st.bar_chart(df["signal"].value_counts())